version: '3.8'
services:
  zookeeper_dev:
    image: wurstmeister/zookeeper:${ZOOKEEPER_VERSION}
    container_name: ${ZOOKEEPER_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${ZOOKEEPER_PORT}:2181

  kafka_dev:
    image: wurstmeister/kafka:${KAFKA_VERSION}
    container_name: ${KAFKA_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${KAFKA_PORT}:9094
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
